ARG BASE_IMAGE_TAG
FROM cobli/helm-client:$BASE_IMAGE_TAG

ARG KUBEVAL_VERSION=0.15.0
ARG KUBEVAL_FILE=kubeval-linux-amd64.tar.gz

RUN apk add --no-cache git=2.20.4-r0 bash=4.4.19-r1

SHELL ["/bin/bash", "-eo", "pipefail", "-c"]
RUN wget "https://github.com/instrumenta/kubeval/releases/download/$KUBEVAL_VERSION/$KUBEVAL_FILE" \
    && wget -O - "https://github.com/instrumenta/kubeval/releases/download/$KUBEVAL_VERSION/checksums.txt" \
        | grep "${KUBEVAL_FILE}" > checksums.txt \
    && sha256sum -c checksums.txt \
    && tar -xzvf $KUBEVAL_FILE kubeval \
    && chmod +x kubeval \
    && mv kubeval /usr/local/bin \
    && rm checksums.txt kubeval-linux-amd64.tar.gz
