version: 2.1

definitions:
  release-tag: &release-tag /^[0-9]+\.[0-9]+\.[0-9]+$/
  image-name: &image-name cobli/helm-client
  helm-version-matrix: &helm-version-matrix

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/hadolint:
          dockerfiles: "Dockerfile,Dockerfile-ci"
      - build-and-push:
          context: coblicd-dockerhub-login
          matrix:
            parameters:
              helm-version: 
                - "3.2.1"
          requires:
            - docker/hadolint

jobs:
  build-and-push:
    executor: docker/machine
    parameters:
      helm-version:
        type: string
    steps:
      - checkout
      - run:
          name: Choose image tag
          environment:
            IMAGE_NAME: *image-name
          command: |-
            tag="<<parameters.helm-version>>"
            if [[ -n $CIRCLE_TAG ]]; then
              tag+="-$CIRCLE_TAG"
            else 
              tag+="-$CIRCLE_BRANCH"
            fi
            echo "export TAG=$tag" >> $BASH_ENV;
      - docker/build:
          step-name: Build slim image
          image: *image-name
          cache_from: cobli/helm-client:<<parameters.helm-version>>
          extra_build_args: --build-arg HELM_VERSION=<<parameters.helm-version>>
          tag: "${TAG}"
      - docker/build:
          step-name: Build CI image
          image: *image-name
          cache_from: cobli/helm-client:<<parameters.helm-version>>
          extra_build_args: --build-arg BASE_IMAGE_TAG=${TAG}
          tag: "ci-${TAG}"
          dockerfile: Dockerfile-ci
      - docker/check
      - docker/push:
          step-name: Push slim image
          image: *image-name
          tag: "${TAG}"
      - docker/push:
          step-name: Push CI image
          image: *image-name
          tag: "ci-${TAG}"

orbs:
  docker: circleci/docker@1.0.1
