version: 2.1

definitions:
  release-tag: &release-tag /^[0-9]+\.[0-9]+\.[0-9]+$/
  image-name: &image-name cobli/helm-client
  helm-version-matrix: &helm-version-matrix
    matrix:
      parameters:
        helm-version: 
          - "3.2.1"

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/hadolint
      - build-and-push:
          <<: *helm-version-matrix
          push: false
          filters:
            branches:
              ignore: /^master$/
            tags:
              ignore: *release-tag
          requires:
            - docker/hadolint
      - build-and-push:
          <<: *helm-version-matrix
          context: coblicd-dockerhub-login
          push: true
          filters:
            branches:
              only: /^master$/
            tags:
              only: *release-tag
          requires:
            - docker/hadolint

jobs:
  build-and-push:
    executor: docker/machine
    parameters:
      helm-version:
        type: string
      push:
        type: boolean
    steps:
      - checkout
      - run:
          name: Choose image tag
          command: |-
            tag="<<parameters.helm-version>>"
            if [[ -n $CIRCLE_TAG ]]; then
              tag+="-$CIRCLE_TAG"
            fi
            echo "export TAG=$tag" >> $BASH_ENV;
      - docker/build:
          image: *image-name
          cache_from: cobli/helm-client:<<parameters.helm-version>>
          extra_build_args: --build-arg HELM_VERSION=<<parameters.helm-version>>
          tag: "${TAG}"
      - when:
          condition: <<parameters.push>>
          steps:
            - docker/check
            - docker/push:
                image: *image-name
                tag: "${TAG}"

orbs:
  docker: circleci/docker@1.0.1
